(custom-set-variables
 '(c-font-lock-keywords my-c++-font-lock-keywords t)
 '(imaxima-scale-factor 1.5)
 '(clearcase-suppress-checkout-comments t)
 '(c-font-lock-keywords-3 my-c++-font-lock-keywords t)
 '(c-font-lock-keywords-2 my-c++-font-lock-keywords t)
 '(c-font-lock-keywords-1 my-c++-font-lock-keywords t)
 '(c++-font-lock-keywords-3 my-c++-font-lock-keywords t)
 '(c++-font-lock-keywords-2 my-c++-font-lock-keywords t)
 '(c++-font-lock-keywords-1 my-c++-font-lock-keywords t)
 '(compilation-font-lock-keywords my-compilation-font-lock-keywords t)
 '(c++-font-lock-keywords my-c++-font-lock-keywords t)
 '(gnuserv-frame (quote gnuserv-special-frame-function))
 '(user-mail-address "belley@discreet.com")
 '(query-user-mail-address nil)
 '(font-lock-maximum-size 1024000))
(custom-set-faces
 '(default ((t (:background "#BBBBBB"))) t)
 '(cperl-nonoverridable-face ((((class color) (background light)) (:foreground "blue"))))
 '(font-lock-string-face ((t (:foreground "purple4"))))
 '(font-lock-reference-face ((t (:foreground "red3" :bold t))))
 '(font-lock-doc-string-face ((t (:foreground "purple4"))))
 '(font-lock-preprocessor-face ((t (:bold t :foreground "purple4"))))
 '(font-lock-variable-name-face ((t (:foreground "blue3"))))
 '(font-lock-warning-face ((((class color) (background light)) (:foreground "yellow" :bold t))))
 '(font-lock-keyword-face ((t (:bold t :foreground "black"))))
 '(font-lock-type-face ((t (:foreground "black"))))
 '(font-lock-other-type-face ((t (:bold t))) t)
 '(font-lock-comment-face ((t (:foreground "blue3"))))
 '(font-lock-function-name-face ((t (:bold t :foreground "#450025")))))
